config/routes.rb
SuggestionBox::Application.routes.draw do
  resources :suggestions

  get 'random' => 'suggestion#random'

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
  # attr_accessible :title, :body
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  attr_accessible :completed, :description, :hours, :minutes, :seconds, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  def random
    @suggestion = Suggestion.first(:order => "RANDOM()")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @suggestion }
    end
  end

  # GET /suggestions
  # GET /suggestions.json
  def index
    @suggestions = Suggestion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @suggestions }
    end
  end

  # GET /suggestions/1
  # GET /suggestions/1.json
  def show
    @suggestion = Suggestion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @suggestion }
    end
  end

  # GET /suggestions/new
  # GET /suggestions/new.json
  def new
    @suggestion = Suggestion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @suggestion }
    end
  end

  # GET /suggestions/1/edit
  def edit
    @suggestion = Suggestion.find(params[:id])
  end

  # POST /suggestions
  # POST /suggestions.json
  def create
    @suggestion = Suggestion.new(params[:suggestion])

    respond_to do |format|
      if @suggestion.save
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully created.' }
        format.json { render json: @suggestion, status: :created, location: @suggestion }
      else
        format.html { render action: "new" }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /suggestions/1
  # PUT /suggestions/1.json
  def update
    @suggestion = Suggestion.find(params[:id])

    respond_to do |format|
      if @suggestion.update_attributes(params[:suggestion])
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suggestions/1
  # DELETE /suggestions/1.json
  def destroy
    @suggestion = Suggestion.find(params[:id])
    @suggestion.destroy

    respond_to do |format|
      format.html { redirect_to suggestions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/home/example.html.haml
.container.text-center
  .row{:style => "position: fixed; padding:10px;z-index:200;margin: 5% auto;top:5%;left: 0;right: 0;"}
    %h1.text-info
      10 MINUTES
    %h3.text-warning
      10 Pushups & 10 Situps... Repeat
  .row{:style => "position: fixed; padding:10px;z-index:200;margin: 5% auto;top:35%;left: 0;right: 0;"}
    .btn.btn-large.btn-success{:style =>"width: 20%; padding-top:20px; padding-bottom:20px;"}
      Begin
  .row{:style =>"position:fixed; bottom: 10%;left:0; right:0;"}
    %blockquote
      %p
        “All we have to decide is what to do with the time that is given us” 
      %small
        J.R.R. Tolkien, The Fellowship of the Ring
.btn.pull-right{:style => "position:fixed; bottom: 0px; right:0px;"}
  next suggestion

app/views/home/index.html.haml
.container.text-center
  .row{:style => "position: fixed; padding:10px;z-index:200;margin: 5% auto;top:15%;left: 0;right: 0;"}
    %h1
      What to do...
  .row{:style => "position: fixed; padding:10px;margin: 5% auto;top:35%;left: 0;right: 0;"}
    %a{:href => suggestion_path(Suggestion.find rand(Suggestion.count )+1 )}
      %button.btn.btn-large.btn-success
        Take A Suggestion
    %a{:href => new_suggestion_path}
      %button.btn.btn-large.btn-primary
        Make A Suggestion
%a.pull-right{:style => "position:fixed; bottom: 4%; right:4%;"}
  About the Community
  

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 2.3
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 2.3
.navbar
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .nav-collapse.collapse
        .navbar.navbar-fixed-top
          %nav.navbar-inner
            %ul.nav
              = link_to 'Home', root_path, class: 'brand'
              = render 'layouts/navigation_links'
            .brand{:style => "position: absolute;width: 100%;left: 0;text-align: center;margin: auto;" }
              Just a Suggestion

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Suggestion Box'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Suggestion Box'}"}
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    -# application layout styled for Bootstrap 2.3
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/suggestions/_form.html.haml
= simple_form_for(@suggestion) do |f|
  = f.error_notification

  .form-inputs
    = f.input :hours
    = f.input :minutes
    = f.input :seconds
    = f.input :title
    = f.input :description

  .form-actions
    = f.button :submit

app/views/suggestions/edit.html.haml
%h1 Editing suggestion

= render 'form'

= link_to 'Show', @suggestion
\|
= link_to 'Back', suggestions_path

app/views/suggestions/index.html.haml
%h1 Listing suggestions

%table
  %tr
    %th Hours
    %th Minutes
    %th Seconds
    %th Title
    %th Description
    %th Completed
    %th
    %th
    %th

  - @suggestions.each do |suggestion|
    %tr
      %td= suggestion.hours
      %td= suggestion.minutes
      %td= suggestion.seconds
      %td= suggestion.title
      %td= suggestion.description
      %td= suggestion.completed
      %td= link_to 'Show', suggestion
      %td= link_to 'Edit', edit_suggestion_path(suggestion)
      %td= link_to 'Destroy', suggestion, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Suggestion', new_suggestion_path

app/views/suggestions/new.html.haml
%h1 New suggestion

= render 'form'

= link_to 'Back', suggestions_path

app/views/suggestions/show.html.haml
.container.text-center
  .row{:style => "position: fixed; padding:10px;z-index:200;margin: 5% auto;top:3%;left: 0;right: 0;"}
    %h1.text-info
      =@suggestion.title
    %br/
    %h4.text-warning
      -if @suggestion.hours
        ="#{@suggestion.hours} HOURS" 
      -if @suggestion.minutes
        ="#{@suggestion.minutes} MINUTES" 
      -if @suggestion.seconds
        ="#{@suggestion.seconds} SECONDS" 
  .row{:style => "position: fixed; padding:10px;z-index:200;margin: 5% auto;top:22%;left: 0;right: 0;"}
    %p.lead.muted.text-center.offset3.span6
      =@suggestion.description
  .row{:style => "position: fixed; padding:10px;z-index:200;margin: 5% auto;top:39%;left: 0;right: 0;"}
    .btn.btn-large.btn-success{:style =>"width: 20%; padding-top:20px; padding-bottom:20px;"}
      Begin
  .row{:style =>"position:fixed; bottom: 10%;left:0; right:0;"}
    %blockquote
      %p
        “All we have to decide is what to do with the time that is given us” 
      %small
        J.R.R. Tolkien, The Fellowship of the Ring
  %div{:style => "position:fixed; bottom: 0px; right:0px;"}
    %a{:href => suggestion_path(Suggestion.find rand(Suggestion.count )+1 )}
      .btn
        next suggestion
    %br/
    or
    %br/
    %a{:href => new_suggestion_path}
      %button.pull-left.btn
        Make A Suggestion
  -#
    %p#notice= notice

    %p
      %b Hours:
      = @suggestion.hours
    %p
      %b Minutes:
      = @suggestion.minutes
    %p
      %b Seconds:
      = @suggestion.seconds
    %p
      %b Title:
      = @suggestion.title
    %p
      %b Description:
      = @suggestion.description
    %p
      %b Completed:
      = @suggestion.completed

    = link_to 'Edit', edit_suggestion_path(@suggestion)
    \|
    = link_to 'Back', suggestions_path

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}